version: '3'

services:
  postgres:
    image: "postgres:14"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: {}